/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.36
 * Generated at: 2020-10-24 13:44:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.admin.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import models.User;
import java.util.List;
import models.User;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/templates/admin/inc/leftbar.jsp", Long.valueOf(1603546328981L));
    _jspx_dependants.put("/templates/admin/inc/footer.jsp", Long.valueOf(1601804341500L));
    _jspx_dependants.put("/templates/admin/inc/header.jsp", Long.valueOf(1603291107119L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("models.User");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\" />\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("    <title>AdminCP | VinaEnter Edu</title>\r\n");
      out.write("    <!-- BOOTSTRAP STYLES-->\r\n");
      out.write("    <link href=\"");
      out.print(request.getContextPath() );
      out.write("/templates/admin/assets/css/bootstrap.css\" rel=\"stylesheet\" />\r\n");
      out.write("    <!-- FONTAWESOME STYLES-->\r\n");
      out.write("    <link href=\"");
      out.print(request.getContextPath() );
      out.write("/templates/admin/assets/css/font-awesome.css\" rel=\"stylesheet\" />\r\n");
      out.write("    <!-- CUSTOM STYLES-->\r\n");
      out.write("    <link href=\"");
      out.print(request.getContextPath() );
      out.write("/templates/admin/assets/css/custom.css\" rel=\"stylesheet\" />\r\n");
      out.write("    <!-- GOOGLE FONTS-->\r\n");
      out.write("    <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css' />\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <div id=\"wrapper\">\r\n");
      out.write("        <nav class=\"navbar navbar-default navbar-cls-top \" role=\"navigation\" style=\"margin-bottom: 0\">\r\n");
      out.write("            <div class=\"navbar-header\">\r\n");
      out.write("                <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\".sidebar-collapse\">\r\n");
      out.write("                    <span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("                    <span class=\"icon-bar\"></span>\r\n");
      out.write("                    <span class=\"icon-bar\"></span>\r\n");
      out.write("                    <span class=\"icon-bar\"></span>\r\n");
      out.write("                </button>\r\n");
      out.write("                <a class=\"navbar-brand\" href=\"index.html\">VinaEnter Edu</a>\r\n");
      out.write("            </div>\r\n");
      out.write("            ");

            	if(session.getAttribute("userInfor") != null){
            		User userInfor = (User) session.getAttribute("userInfor");
            		
      out.write("<div style=\"color: white;padding: 15px 50px 5px 50px;float: right;font-size: 16px;\">\r\n");
      out.write("            \t\t\t\t Xin chào, <b>");
      out.print(userInfor.getFullname());
      out.write("</b> &nbsp; \r\n");
      out.write("\t\t\t\t            <a href=\"");
      out.print(request.getContextPath() );
      out.write("/auth/logout\" class=\"btn btn-danger square-btn-adjust\">Đăng xuất</a> \r\n");
      out.write("\t\t\t\t         </div>\r\n");
      out.write("            \t\t");

            	}else{
            		
      out.write("<div style=\"color: white;padding: 15px 50px 5px 50px;float: right;font-size: 16px;\">\r\n");
      out.write("\t   \t\t\t\t Xin chào, <b>admin</b> &nbsp; \r\n");
      out.write("\t\t\t            <a href=\"");
      out.print(request.getContextPath() );
      out.write("/auth/\" class=\"btn btn-danger square-btn-adjust\">Đăng xuất</a> \r\n");
      out.write("\t\t\t         </div>\r\n");
      out.write("            \t\t");

            	}
            
      out.write("</nav>\r\n");
      out.write("        <!-- /. NAV TOP  -->");
      out.write("<nav class=\"navbar-default navbar-side\" role=\"navigation\">\r\n");
      out.write("\t\t\t    <div class=\"sidebar-collapse\">\r\n");
      out.write("\t\t\t    ");

			    	// mapping url
			    	// /admin/cat/index
  	  				String urlSlugCat = request.getContextPath()+"/admin/quan-ly-danh-muc"+".html";
				    String urlSlugSong = request.getContextPath()+"/admin/quan-ly-bai-hat"+".html";
				    String urlSlugUser = request.getContextPath()+"/admin/quan-ly-nguoi-dung"+".html";
				    String urlSlugContact = request.getContextPath()+"/admin/quan-ly-lien-he"+".html";
			    
      out.write("<ul class=\"nav\"id=\"main-menu\">\r\n");
      out.write("\t\t\t            <li class=\"text-center\">\r\n");
      out.write("\t\t\t                <img src=\"");
      out.print(request.getContextPath() );
      out.write("/templates/admin/assets/img/find_user.png\" class=\"user-image img-responsive\" />\r\n");
      out.write("\t\t\t            </li>\r\n");
      out.write("\t\t\t            <li>\r\n");
      out.write("\t\t\t                <a id=\"index\" href=\"");
      out.print(request.getContextPath());
      out.write("/admin\"><i class=\"fa fa-dashboard fa-3x\"></i> Trang chủ</a>\r\n");
      out.write("\t\t\t            </li>\r\n");
      out.write("\t\t\t            <li>\r\n");
      out.write("\t\t\t                <a id=\"category\" href=\"");
      out.print(urlSlugCat);
      out.write("\"><i class=\"fa fa-list fa-3x\"></i> Quản lý danh mục</a>\r\n");
      out.write("\t\t\t            </li>\r\n");
      out.write("\t\t\t            <li>\r\n");
      out.write("\t\t\t                <a id=\"song\" href=\"");
      out.print(urlSlugSong);
      out.write("\"><i class=\"fa fa-music fa-3x\"></i> Quản lý bài hát</a>\r\n");
      out.write("\t\t\t            </li>\r\n");
      out.write("\t\t\t            <li>\r\n");
      out.write("\t\t\t                <a id=\"user\" href=\"");
      out.print(urlSlugUser);
      out.write("\"><i class=\"fa fa-user fa-3x\"></i> Quản lý người dùng</a>\r\n");
      out.write("\t\t\t            </li>\r\n");
      out.write("\t\t\t            <li>\r\n");
      out.write("\t\t\t                <a id=\"contact\" href=\"");
      out.print(urlSlugContact);
      out.write("\"><i class=\"fa fa-envelope fa-3x\"></i> Quản lý liên hệ</a>\r\n");
      out.write("\t\t\t            </li>\r\n");
      out.write("\t\t\t        </ul>\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t\t</nav>\r\n");
      out.write("\t\t\t<script type=\"text/javascript\">\n");
      out.write("\t\t\t\tif(window.location.hash) {\t\r\n");
      out.write("\t\t\t\t\tvar hash = window.location.hash.substring(1);\t\r\n");
      out.write("\t\t\t\t\t$('.nav a[id=\"' + hash + '\"]').tab('show');\r\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t</script>\r\n");
      out.write("\t\t\t<!-- /. NAV SIDE  -->\r\n");
      out.write("    \t");
      out.write("<div id=\"page-wrapper\">\r\n");
      out.write("    <div id=\"page-inner\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-md-12\">\r\n");
      out.write("                <h2>Quản lý tài khoản</h2>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- /. ROW  -->\r\n");
      out.write("        <hr />\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-md-12\">\r\n");
      out.write("                <!-- Advanced Tables -->\r\n");
      out.write("                <div class=\"panel panel-default\">\r\n");
      out.write("                    <div class=\"panel-body\">\r\n");
      out.write("                        <div class=\"table-responsive\">\r\n");
      out.write("                            <div class=\"row\">\r\n");
      out.write("                                <div class=\"col-sm-6\">\r\n");
      out.write("                                    <a href=\"");
      out.print(request.getContextPath() );
      out.write("/admin/user/add\" class=\"btn btn-success btn-md\">Thêm</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-sm-6\" style=\"text-align: right;\">\r\n");
      out.write("                                    <form method=\"GET\" action=\"");
      out.print(request.getContextPath());
      out.write("/admin/user/index\">\r\n");
      out.write("                                        <input type=\"submit\" name=\"search\" value=\"Tìm kiếm\" class=\"btn btn-warning btn-sm\" style=\"float:right\" />\r\n");
      out.write("                                        <input type=\"search\" name=\"nameUser\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nameUser}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"class=\"form-control input-sm\" placeholder=\"Nhập tên bài hát\" style=\"float:right; width: 300px;\" />\r\n");
      out.write("                                        <div style=\"clear:both\"></div>\r\n");
      out.write("                                    </form><br />\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <table class=\"table table-striped table-bordered table-hover\" id=\"dataTables-example\">\r\n");
      out.write("                                <thead>\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                        <th>STT</th>\r\n");
      out.write("                                        <th>Tên đăng nhập</th>\r\n");
      out.write("                                        <th>Tên đầy đủ</th>\r\n");
      out.write("                                        <th width=\"160px\">Chức năng</th>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                </thead>\r\n");
      out.write("                                <tbody>\r\n");
      out.write("                                ");

                                	if(request.getAttribute("user") != null){
                                		List<User> userList = (List<User>) request.getAttribute("user");
                                		if(userList.size() > 0){
                                			

		                                			int i = 0;
			                                		for(User user : userList){
			                                			i++;
			                                			int id = user.getId();
			                                			String username = user.getUsername();
			                                			String fullname = user.getFullname();
			                                			String urlEdit = request.getContextPath()+"/admin/user/edit?uid="+id;
			                                			String urlDel = request.getContextPath()+"/admin/user/del?uid="+id;
			                                			
      out.write("<tr>\r\n");
      out.write("\t\t\t\t\t\t                                        <td>");
      out.print(i );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t                                        <td class=\"center\">");
      out.print(username );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t                                        <td class=\"center\">");
      out.print(fullname );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t                                        <td class=\"center\">\r\n");
      out.write("\t\t\t\t\t\t                                            <a href=\"");
      out.print(urlEdit );
      out.write("\" title=\"\" class=\"btn btn-primary\"><i class=\"fa fa-edit \"></i> Sửa</a>\r\n");
      out.write("\t\t\t\t\t\t                                            <a href=\"");
      out.print(urlDel );
      out.write("\" title=\"\" class=\"btn btn-danger\"><i class=\"fa fa-pencil\"></i> Xóa</a>\r\n");
      out.write("\t\t\t\t\t\t                                        </td>\r\n");
      out.write("\t\t\t\t\t\t                                    </tr>\r\n");
      out.write("\t\t\t                                \t\t\t");

			                                		}
	                                			

		                                			int numberOfPage = (Integer)request.getAttribute("numberOfPage");
		                                		  	int currentPage = (Integer)request.getAttribute("currentPage");
		                                		  	if(userList != null && userList.size() > 0){
		                                		  		
      out.write("<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t                                <!-- <div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t\t                                    <div class=\"dataTables_info\" id=\"dataTables-example_info\" style=\"margin-top:27px\">Hiển thị từ 1 đến 5 của 24 truyện</div>\r\n");
      out.write("\t\t\t\t\t\t\t                                </div> -->\r\n");
      out.write("\t\t\t\t\t\t\t                                <div class=\"col-sm-6\" style=\"text-align: right;\">\r\n");
      out.write("\t\t\t\t\t\t\t                                    <div class=\"dataTables_paginate paging_simple_numbers\" id=\"dataTables-example_paginate\">\r\n");
      out.write("\t\t\t\t\t\t\t                                        <ul class=\"pagination\">\r\n");
      out.write("\t\t\t\t\t\t\t                                        <!-- <li class=\"paginate_button previous disabled\" aria-controls=\"dataTables-example\" tabindex=\"0\" id=\"dataTables-example_previous\"><a href=\"#\">Trang trước</a></li> -->\r\n");
      out.write("\t\t\t\t\t\t\t                                        ");

							                                        	for(int j = 1; j <= numberOfPage; j++){
							                                        		

									                                        		if(currentPage == j){
								                                        				
      out.write("<li class=\"paginate_button active\" aria-controls=\"dataTables-example\" tabindex=\"0\"><a href=\"\">");
      out.print(j);
      out.write("</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t                                        \t\t\t\t");

								                                        			}else{
								                                        				
      out.write("<li class=\"paginate_button\" aria-controls=\"dataTables-example\" tabindex=\"0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t                                        \t\t\t\t\t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("/admin/user/index?page=");
      out.print(j);
      out.write('"');
      out.write('>');
      out.print(j);
      out.write("</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t                                        \t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t                                        \t\t\t\t");

								                                        			}
								                                        		

							                                        	}
							                                        
      out.write("<!-- <li class=\"paginate_button next\" aria-controls=\"dataTables-example\" tabindex=\"0\" id=\"dataTables-example_next\"><a href=\"#\">Trang tiếp</a></li> -->\r\n");
      out.write("\t\t\t\t\t\t\t                                        </ul>\r\n");
      out.write("\t\t\t\t\t\t\t                                    </div>\r\n");
      out.write("\t\t\t\t\t\t\t                                </div>\r\n");
      out.write("\t\t\t\t\t\t\t                            </div>\r\n");
      out.write("\t\t                                \t\t  \t\t");

		                                		  	}
	                                			

                                		}else{
                                			
      out.write("<div class=\"article\">\r\n");
      out.write("                            \t\t\t\t\t<h1>Không có tài khoản</h1>\r\n");
      out.write("                            \t\t\t\t</div>\r\n");
      out.write("                              \t\t\t\t");

                                		}
                                	}
                                
      out.write("</tbody>\r\n");
      out.write("                            </table>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!--End Advanced Tables -->\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<script>\r\n");
      out.write("    document.getElementById(\"song\").classList.add('active-menu');\r\n");
      out.write("</script>\r\n");
      out.write("<!-- /. PAGE INNER  -->\r\n");
      out.write("</div>\r\n");
      out.write("<!-- /. WRAPPER  -->\r\n");
      out.write("<!-- SCRIPTS -AT THE BOTOM TO REDUCE THE LOAD TIME-->\r\n");
      out.write("<!-- JQUERY -->\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/templates/admin/assets/js/jquery-3.2.1.js\"></script>\r\n");
      out.write("<!-- BOOTSTRAP SCRIPTS -->\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/templates/admin/assets/js/bootstrap.min.js\"></script>\r\n");
      out.write("<!-- METISMENU SCRIPTS -->\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/templates/admin/assets/js/jquery.metisMenu.js\"></script>\r\n");
      out.write("<!-- CUSTOM SCRIPTS -->\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/templates/admin/assets/js/custom.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
